version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      medusa:
        patterns:
          - "@medusajs/*"
      types:
        patterns:
          - "@types/*"
      dev-tooling:
        patterns:
          - "eslint*"
          - "prettier"
          - "typescript*"
          - "jest*"
          - "@swc/*"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
